version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus
    ports:
      - "9190:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

