version: '3'
services:
  eureka:
    image: atai2/at-eureka
    restart: always
    ports:
      - 8761:8761

  monitor:
    image: atai2/at-monitor
    restart: always
    ports:
      - 8000:8000
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

  usermanager:
    image: atai2/at-user-management
    restart: always
    ports:
    - 9000:9000
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      spring.boot.adminc.lient.url: http://94.191.68.209:8000
