version: 3
services:
  flink-master:
    image: bde2020/flink-master:1.12.2-hadoop3.2
    hostname: flink-master
    container_name: flink-master
    environment:
      - INIT_DAEMON_STEP=setup_flink
    #     - "constraint:node==<yourmasternode>"

    ports:
      - "8080:8080"
      - "8081:8081"

  flink-worker:
    image: bde2020/flink-worker:1.12.2-hadoop3.2
    hostname: flink-worker
    container_name: flink-worker
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
    #    - FLINK_NUM_TASK_SLOTS=2
    #    - "constraint:node==<yourworkernode>"
    depends_on:
      - "flink-master"