version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    deploy:
      resources:
        limits:
          memory: 256m
    container_name: mysqlmall
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: asdf@1234
      MYSQL_DATABASE: atshopauth
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"

  redis:
    image: redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
    ports:
      - 16379:6379
    command: redis-server --requirepass rootatai  --notify-keyspace-events Egl
