server:
  port: 9140

eureka:
  client:
    serviceUrl:
      defaultZone: http://94.191.68.209:8761/eureka/

management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: '*'
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: at-password
#  data:
#    redis:
#      repositories:
#        enabled: false
  boot:
    admin:
      client:
        url: http://127.0.0.1:8769


logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug


