version: '3'
services:
  eureka:
    image: atai2/at-eureka
    restart: always
    ports:
      - 8761:8761

  monitor:
    image: atai2/at-monitor
    restart: always
    ports:
      - 8000:8000
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
