version: '3'
services:
  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123456
    volumes:
    - server:/data
    command: server /data

