server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://94.191.68.209:8761/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#

spring:
  # 应用程序名称
  application:
    name: at-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://at-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: goods
#          uri: http://localhost:9020
          uri: lb://at-goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
        - id: item
#          uri: http://localhost:9020
          uri: lb://at-items
          predicates:
            - Path=/items/**
          filters:
            - StripPrefix=1

    # 服务注册和配置
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yml
#        group: atshop
