server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://94.191.68.209:8761/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#

spring:
  # 应用程序名称
  application:
    name: at-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:9120
          predicates:
            - Method=GET,POST,PUT,DELETE
    # 服务注册和配置
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yml
#        group: atshop
